-- 하트비트 **밖에서** 얻은 마지막 생존 증거를 기록한다
-- (로드맵 `#61` 4단계).
--
-- `on_demand` 워커는 idle일 때 heartbeat을 보내지 않는다. 그래서 그 워커의
-- `last_seen`은 **join 시점에 멈춘 채 영영 움직이지 않는다** — 운영자 화면과
-- API가 보여 주는 유일한 생존 지표가 등록 이후로 갱신되지 않는다는 뜻이다.
--
-- 그런데 증거는 이미 얻고 있었다. `#70` 게이트 5가 넣은 dispatch 직전 ACP
-- probe는 그 워커가 **지금** 답한다는 것을 왕복으로 확인하는데, 그 결과가
-- `selector.rs`의 `debug!`/`warn!` 한 줄로 끝나고 아무 데도 남지 않았다.
-- 얻어 놓고 버린 사실이다.
--
-- `last_seen`을 재사용하지 않는 이유는 그 컬럼의 뜻이 "마지막 **하트비트**
-- 수신 시각"이기 때문이다(`worker.rs`의 독스트링, 그리고 `HealthChecker`와
-- `Reconciler`의 offline 유예 판정이 전부 그 뜻에 기대고 있다). probe 성공을
-- 거기에 적으면 heartbeat을 보내지 않는 워커가 heartbeat을 보낸 것처럼
-- 보이고, `offline_worker_grace` 판정이 조용히 뜻을 잃는다.
ALTER TABLE workers ADD COLUMN last_activity_at TIMESTAMPTZ;

-- 기존 행은 채우지 않는다. `last_seen`으로 backfill하면 "하트비트 밖에서 얻은
-- 증거"라는 이 컬럼의 뜻이 첫 행부터 거짓이 된다 — `042`가 증명 가능한
-- 상한을 채운 것과 달리, 여기서 채울 값은 **다른 사실**이지 같은 사실의
-- 느슨한 추정이 아니다.
